services:
  db:
    container_name: musicplay_db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: musicplay_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: musicplay_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/musicplay_db
    depends_on:
      - db
    # volumes:
    #   - ./backend:/app

  frontend:
    container_name: musicplay_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    depends_on:
      - api

volumes:
  pgdata:
